-- MySQL Script generated by MySQL Workbench
-- Mon Feb 28 23:45:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apimovies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apimovies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apimovies` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `apimovies` ;

-- -----------------------------------------------------
-- Table `apimovies`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apimovies`.`generos` ;

CREATE TABLE IF NOT EXISTS `apimovies`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apimovies`.`peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apimovies`.`peliculas` ;

CREATE TABLE IF NOT EXISTS `apimovies`.`peliculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `calificacion` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `generoId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_generoId_idx` (`generoId` ASC) VISIBLE,
  CONSTRAINT `fk_generoId`
    FOREIGN KEY (`generoId`)
    REFERENCES `apimovies`.`generos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apimovies`.`personajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apimovies`.`personajes` ;

CREATE TABLE IF NOT EXISTS `apimovies`.`personajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `edad` DECIMAL(10,0) NOT NULL,
  `peso` DECIMAL(10,0) NOT NULL,
  `historia` VARCHAR(50) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apimovies`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apimovies`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `apimovies`.`usuarios` (
  `id` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apimovies`.`personaje_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apimovies`.`personaje_pelicula` ;

CREATE TABLE IF NOT EXISTS `apimovies`.`personaje_pelicula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personajeId` INT NOT NULL,
  `peliculaId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personajeId_idx` (`personajeId` ASC) VISIBLE,
  INDEX `fk_peliculaId_idx` (`peliculaId` ASC) VISIBLE,
  CONSTRAINT `fk_personajeId`
    FOREIGN KEY (`personajeId`)
    REFERENCES `apimovies`.`personajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peliculaId`
    FOREIGN KEY (`peliculaId`)
    REFERENCES `apimovies`.`peliculas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
